name: Generate Wiki Docs

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  gendoc:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out the main repository
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # 2️⃣ Check out the wiki repository into ./wiki
      - name: Check out wiki
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki

      # 3️⃣ Generate documentation
      - name: Generate documentation
        run: make gendoc

      # 4️⃣ Commit and push changes in ./wiki
      - name: Commit & Push wiki changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "docs: update generated documentation"
          branch: master
          repository: wiki
